### ISSUE TITLE
install file does not exist

### ISSUE THREAD

**Issue by WannaCryCryCryCry** [Philesiv/XSLeaker#5]
the install file does not exist in the folders.
it is therefore impossible to do the "yarn install" command in order to install the dependencies

**Comment by Philesiv** [comment]
Which install files are you missing? After installing yarn (classic) via npm (https://classic.yarnpkg.com/lang/en/docs/install/#windows-stable) "yarn install" should work.

**Comment by Philesiv** [comment]
Sorry for closing ;)

**Comment by Philesiv** [comment]
I just cloned the repo and made a fresh install. Everything is working as expected. Maybe you are using yarn2?

**Comment by WannaCryCryCryCry** [comment]
Hi,
I think it doesn't work because I didn't install it with npm...

![image](https://user-images.githubusercontent.com/77116294/195869575-916f98d4-5d0d-44d5-8529-7ac02efe7012.png)

**Comment by WannaCryCryCryCry** [comment]
I have this error when i execute it

![image](https://user-images.githubusercontent.com/77116294/195870139-3456fbd4-1667-45bd-8cc5-feade09615f6.png)

**Comment by Philesiv** [comment]
The yarn version seems to be very outdated, install it with npm and all should work fine.

**Comment by WannaCryCryCryCry** [comment]
It's okay, everything work thanks !
